### ISSUE TITLE
Constructor Flexibility/Silent Failures

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/DFOLS.jl#3]
Running this solver for one of the problems I was working resulted in an immediate "silent" failure --- i.e., exit immediately with the starting point and `Inf` residuals. 

The problem is that `soln[:jacobian]` is `nothing` at that point, and the constructor is expecting `Matrix{TF <: AbstractFloat}`. So we neither threw a descriptive `soln[:msg]` nor returned an object with solver results. 

Basically, maybe we can: 

* Change the type constraints for the fields to `Union{Nothing, WhateverTheTypeIs}`
* If even that doesn't work, and we've made it past the `soln[:EXIT_SUCCESS_FLAG]` or whatever, just return the `PyObject` which you can get fields from using PyCall.

**Comment by jlperla** [comment]
So is the issue that the underlying python can't handle when the function it calls returns `Inf` or `NaN` or things like that?  Or is it just that it returns correctly, but the jacobian is `nothing`?  If the latter, then the easiest approach is to make the https://github.com/QuantEcon/DFOLS.jl/blob/master/src/DFOLS.jl#L10 more generic.  for example the `x`, `resid` and `jacobian` could all just be left as completely generic parameters.  Or put in a union if you can figure it out correctly... I suspect generic duck typed is easier.

Regardless, add it to the unit tests.

**Comment by arnavs** [comment]
The issue with the constructor was the latter case (more clearly, that if you exit on the first run, and slip past the convergence check then your Jacobian will be `nothing`). For now, I just made this a Union and added a unit test with the residuals function `f = x -> [0., 0.]`, which reproduces the error. 

Later we can confirm that the underlying Python is OK in these kinds of pathological cases (but it seems like it is).
